### ISSUE TITLE
OMTD fields and labels

### ISSUE THREAD

**Issue by kgiann78** [openminted/content-connector-core#3]
In order to provide common casing in fields and common labels to all content connectors there have been implemented in content-connector-api (GitHub.com/openminted/content-connector-api) the following:
1. OMTDFacetEnum - OMTD names that are used for faceting
2. OMTDFacetInitializer - Class that contains maps for labelling according to different facet types
3. Language converter - Brings different connectors' languages to OMTD language
4. RightsStmtNameConverter - To convert names for rights

Each connector should use the above in order to come up with a common terminology in queries.

Pls check also PublicationTypes and any other result that has to be converted to the corresponding OMTD type

**Comment by kgiann78** [comment]
Also, don't forget to check proper names of fields when asking CORE with OMTD facets

**Comment by kgiann78** [comment]
When we perform a search with OMTD fields, in many cases CORE won't respond because there isn't the proper matching

**Comment by anastluc** [comment]
@kgiann78 in what cases does this happen? Can you provide a couple (or more) of example queries that this mismatch happens

**Comment by kgiann78** [comment]
When we perform a filtered search with OMTD fields, in many cases CORE will respond with no results. It seems that there isn't the proper matching. Given an example:
1. Open page at dev.openminted.eu
2. From the menu head at Actions and Access OA Docs
3. From the Publication Type (to the left) if you select anything you will see that there are no results from CORE. Only OpenAIRE results.
4. Also the same happens in Languages and I believe in other selections too.

**Comment by anastluc** [comment]
@kgiann78 please confirm that issue has been resolved after the last commit 374b3dd (in /debugging branch)
