### ISSUE TITLE
Check Facets' Values

### ISSUE THREAD

**Issue by kgiann78** [openminted/content-connector-core#5]
In order to achieve full merging of content providers in content-service all values of each facet should be checked for proper naming and values

**Comment by anastluc** [comment]
Facets names have been checked, awaiting confirmation via ARC dev team.
Example responses in /browse request for 
{"params":{"publicationyear":["2016"],"source":["CORE"]},"keyword":"bitcoin"}
and
{"params":{"publicationyear":["2016"],"source":["OpenAIRE"]},"keyword":"bitcoin"}
for both providers is provided in files attached 

[example_query_CORE.txt](https://github.com/openminted/content-connector-core/files/1225245/example_query_CORE.txt)
[example_query_OpenAIRE.txt](https://github.com/openminted/content-connector-core/files/1225246/example_query_OpenAIRE.txt)
