### ISSUE TITLE
Language code mapping

### ISSUE THREAD

**Issue by kgiann78** [openminted/content-connector-core#8]
I am opening a new issue just for Language issue... 
We both have #456 and #452 tickets in redmine so I was working to change the schema of the language mappings in order to provide only specific values, accepted from the omtd schema.

Check the new module content-connector-utils and more specific the LanguageUtils. Since language names can be most likely confused or misspelled, the only valid way to do it is to filter by the code of the language. i.e. For English is en or eng (depending the ISO you use). 

LanguageUtils contains all necessary conversion maps from any ISO to the OMTD code and the labels to display and vice versa

**Comment by anastluc** [comment]
This is being addressed in the last commits of the debunking branch, see https://github.com/openminted/content-connector-core/commit/baa336a3584520e2e3f427ffc47b948f6ead2053 and https://github.com/openminted/content-connector-core/commit/bcfefda245b0d5c0d0e4f297413cb4ca0baf2526
